#!/usr/bin/env bun
import { PathStore } from '@pierre/path-store';
import {
  getVirtualizationWorkload,
  sortCanonicalPaths,
} from '@pierre/tree-test-data';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve as resolvePath } from 'node:path';
import { gzipSync } from 'node:zlib';

import { AOSP_PREVIEW_PATHS } from '../app/trees-dev/_lib/aospPreview';
import type {
  BulkExperimentExpansionMode,
  BulkExperimentVisibleCountByExpansionMode,
  BulkExperimentWorkloadName,
} from '../app/trees-dev/_lib/bulkExperimentMeta';
import {
  BULK_EXPERIMENT_WORKLOAD_NAMES,
  BULK_PREVIEW_PATH_COUNT,
  getBulkExperimentExpansionOptions,
} from '../app/trees-dev/_lib/bulkExperimentMeta';
import { deriveAllExpandedPaths } from '../app/trees-dev/_lib/deriveAllExpandedPaths';
import { AOSP_UPGRADE_DATA_URL } from '../app/trees-dev/_lib/workloadMeta';

interface GeneratedPreviewEntry {
  finalVisibleCountByExpansionMode: BulkExperimentVisibleCountByExpansionMode;
  previewPaths: readonly string[];
  previewVisibleCountByExpansionMode: BulkExperimentVisibleCountByExpansionMode;
  totalPathCount: number;
}

const repoRoot = resolvePath(import.meta.dirname, '../../..');
const outputDir = resolvePath(repoRoot, 'apps/docs/public/trees-dev');
const previewOutputPath = resolvePath(
  repoRoot,
  'apps/docs/app/trees-dev/_lib/bulkExperimentPreviewData.ts'
);
const aospSourcePath = resolvePath(
  repoRoot,
  'packages/tree-test-data/aosp-files.json'
);

const previewEntries: Record<string, GeneratedPreviewEntry> = {};
mkdirSync(outputDir, { recursive: true });

function createVisibleCountByExpansionMode(
  paths: readonly string[],
  workloadName: BulkExperimentWorkloadName
): BulkExperimentVisibleCountByExpansionMode {
  const preparedInput = PathStore.preparePresortedInput(paths);
  return {
    'all-open': getVisibleCountForExpansionMode(
      preparedInput,
      workloadName,
      'all-open'
    ),
    'all-closed': getVisibleCountForExpansionMode(
      preparedInput,
      workloadName,
      'all-closed'
    ),
    seeded: getVisibleCountForExpansionMode(
      preparedInput,
      workloadName,
      'seeded'
    ),
  };
}

// Builds the exact visible-row counts the bulk demo needs so fixed workloads
// can reserve truthful geometry without recomputing full projections at runtime.
function getVisibleCountForExpansionMode(
  preparedInput: ReturnType<typeof PathStore.preparePresortedInput>,
  workloadName: BulkExperimentWorkloadName,
  expansionMode: BulkExperimentExpansionMode
): number {
  const store = new PathStore({
    flattenEmptyDirectories: false,
    ...getBulkExperimentExpansionOptions(workloadName, expansionMode),
    preparedInput,
  });
  return store.getVisibleCount();
}

function createPreviewEntry(
  workloadName: BulkExperimentWorkloadName,
  paths: readonly string[],
  previewPaths: readonly string[]
): GeneratedPreviewEntry {
  return {
    finalVisibleCountByExpansionMode: createVisibleCountByExpansionMode(
      paths,
      workloadName
    ),
    previewPaths,
    previewVisibleCountByExpansionMode: createVisibleCountByExpansionMode(
      previewPaths,
      workloadName
    ),
    totalPathCount: paths.length,
  };
}

console.log(`[bulk] reading ${aospSourcePath}`);
const aospPaths = sortCanonicalPaths(
  JSON.parse(readFileSync(aospSourcePath, 'utf8')) as string[]
);

for (const workloadName of BULK_EXPERIMENT_WORKLOAD_NAMES) {
  if (workloadName === 'aosp') {
    const previewPaths = AOSP_PREVIEW_PATHS.slice(0, BULK_PREVIEW_PATH_COUNT);
    previewEntries[workloadName] = createPreviewEntry(
      workloadName,
      aospPaths,
      previewPaths
    );
    console.log(`[bulk] aosp preview reuses ${AOSP_UPGRADE_DATA_URL}`);
    continue;
  }

  const workload = getVirtualizationWorkload(workloadName);
  const allExpandedPaths = deriveAllExpandedPaths(workload.presortedFiles);
  const payload = JSON.stringify({
    allExpandedPaths,
    paths: workload.presortedFiles,
  });
  const gz = gzipSync(payload, { level: 9 });
  const outputPath = resolvePath(outputDir, `${workloadName}.json.gz`);
  writeFileSync(outputPath, gz);

  previewEntries[workloadName] = createPreviewEntry(
    workloadName,
    workload.presortedFiles,
    workload.presortedFiles.slice(0, BULK_PREVIEW_PATH_COUNT)
  );

  console.log(
    `[bulk] ${workloadName} → ${outputPath} (${(gz.byteLength / 1024 / 1024).toFixed(1)} MB, from ${(payload.length / 1024 / 1024).toFixed(1)} MB)`
  );
}

const previewContent = `// Generated by apps/docs/scripts/generateBulkExperimentArtifacts.ts. Do not edit by hand.
import type {
  BulkExperimentVisibleCountByExpansionMode,
  BulkExperimentWorkloadName,
} from './bulkExperimentMeta';

export interface BulkExperimentPreviewData {
  finalVisibleCountByExpansionMode: BulkExperimentVisibleCountByExpansionMode;
  previewPaths: readonly string[];
  previewVisibleCountByExpansionMode: BulkExperimentVisibleCountByExpansionMode;
  totalPathCount: number;
}

export const BULK_EXPERIMENT_PREVIEW_DATA = ${JSON.stringify(previewEntries, null, 2)} satisfies Record<BulkExperimentWorkloadName, BulkExperimentPreviewData>;
`;

writeFileSync(previewOutputPath, previewContent, 'utf8');
console.log(`[bulk] preview data → ${previewOutputPath}`);
